kind: Service                             
apiVersion: v1
metadata:
  name: demowebsite
  labels:
    app: demowebsite
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: demowebsite                  
  type: LoadBalancer       
